# Generated by Django 5.2 on 2026-07-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
